// Deep, differentiated content for industry & show pages.
// Verified facts carry source + date. Judgments are labelled by tone in copy.

export const SHOW_VERIFIED = {
  "ciff-guangzhou": {
    startDate: "2027-03-18",
    nextEdition: "59th edition: 18–21 March 2027 (Home Furniture) · 28–31 March 2027 (Office & Commercial Space, CIFM/interzum)",
    venueExact: "Canton Fair Complex (Pazhou) & PWTC Expo, Guangzhou",
    phasesExact: "Days 1–4 (18–21 Mar): home furniture, home decor & hometextile, outdoor & leisure; days 5–8 (28–31 Mar): office & commercial space, healthcare/senior-care furniture, CIFM/interzum (materials, hardware, machinery)",
    buyersFit: "Furniture importers & retail chains, designers & fit-out contractors, hotel/apartment project buyers, office-furniture dealers, component buyers.",
    arrivalAdvice: "Book hotels in Pazhou or along metro access to both venues. Arrive at least 1 day before your phase start. Pre-register online — registration at the door is slower.",
    nearbyClusters: "Foshan Lecong furniture market (30–70 min drive), Shunde case-goods factories, Zhongshan lighting (60–90 min).",
    source: "https://www.ciff-gz.com/en/",
    lastVerified: "2026-09-20",
    verified: true,
    registrationLink: "https://www.ciff-gz.com/en/ (pre-register → Become a Visitor)",
    faqs: [
      ["Is CIFF Guangzhou worth visiting for a first-time furniture buyer?", "If your list spans furniture categories or you also buy decor/lighting, yes: one fair day covers more suppliers than a week of showroom visits. If you only need one known product family, a direct Foshan factory run may be more efficient."],
      ["Do I need to attend both stages (both date blocks)?", "Home furniture buyers rarely need the office/materials block; project buyers (office, hotel) more often do. We plan your trip around your product list, not the full fair."],
      ["When should supplier visits be scheduled?", "Between the two date blocks or after your last fair day — factory days collide with fair-walking otherwise."],
    ],
  },
  cips: {
    startDate: "2026-11-12",
    nextEdition: "CIPS 2026 — 30th edition: 12–15 November 2026",
    venueExact: "China Import and Export Fair Complex (Pazhou), Guangzhou",
    phasesExact: "Four days: Thu–Sat 10:00–17:30, Sun 10:00–14:00. Zones cover pet supplies, aquatics, pet food, e-commerce and retail services, with B2B matchmaking.",
    buyersFit: "Pet retailers, importers, distributors and e-commerce sellers looking for manufacturing sources and new ranges.",
    arrivalAdvice: "Guangzhou Baiyun airport by Wednesday 11 Nov at the latest; Pazhou hotels sell out for this fair — book 3–4 weeks ahead. Register via the official online system.",
    nearbyClusters: "Pet-product factories cluster in Zhejiang (Pingyang), Jiangsu (Yangzhou) and Guangdong (Dongguan/Shenzhen). Guangzhou toy/accessory wholesale composes well with fair days.",
    source: "https://en.cipscom.com/",
    lastVerified: "2026-09-20",
    verified: true,
    registrationLink: "https://en.cipscom.com/ (Visitor → Registration)",
    faqs: [
      ["Is CIPS useful if I only sell non-food pet products?", "Yes — supplies, aquatics and gear form the largest exhibit zones; food is a smaller share of the floor."],
      ["Does the show run B2B matchmaking?", "The organizer runs a matchmaking program for pre-registered buyers; our supplier trip adds factory-level visits the fair cannot host."],
    ],
  },
  "hotelex-shanghai": {
    startDate: "2027-03-30",
    nextEdition: "HOTELEX Shanghai 2027: 30 March – 2 April 2027 (organizer also lists 2026 editions: Shenzhen 13–15 Oct, Guangzhou 11–13 May, Chengdu 2–4 Jul)",
    venueExact: "Shanghai — see the organizer's registration page for the current hall layout (typically SNIEC)",
    phasesExact: "Ten product sections: coffee & tea, beverages, food & ingredients, catering equipment, tabletop, bakery & light meals, private label & OEM, wine & spirits, gifts & lifestyle, catering supply chain.",
    buyersFit: "Restaurant / café / bakery / hotel owners equipping projects, equipment distributors, F&B importers, coffee & tea channels.",
    arrivalAdvice: "Fair dates sit near CIFF Guangzhou — many buyers run both. Preshanghai hotels near the venue sell out; reserve ahead and register online early.",
    nearbyClusters: "Foshan & Jiangmen kitchen-stainless fabrication, Guangzhou hospitality-equipment market, Jiangmen/Shenzhen coffee-equipment suppliers.",
    source: "https://www.hotelex.cn/",
    lastVerified: "2026-09-20",
    verified: true,
    registrationLink: "https://www.hotelex.cn/ (观众注册 / visitor registration)",
    faqs: [
      ["Is HOTELEX right for opening a restaurant, or only for big buyers?", "Both: the fair covers equipment, tabletop and ingredients in one venue, which fits a project buyer outfitting one or several outlets."],
      ["Can we buy a small mixed equipment set after visiting?", "Many exhibitors accept small mixed orders; we schedule follow-up quotes around your exact configuration."],
    ],
  },
  chinaplas: {
    startDate: "2027-04-13",
    nextEdition: "CHINAPLAS 2027: 13–16 April 2027",
    venueExact: "Shenzhen World Exhibition & Convention Center (Bao'an), Shenzhen",
    phasesExact: "Single edition covering plastics & rubber machinery, materials, and application industries (packaging, automotive, electronics, medical etc.).",
    buyersFit: "Manufacturers investing in plastics machinery, packaging producers, materials buyers, automation buyers.",
    arrivalAdvice: "Shenzhen Bao'an airport is next to the venue; book hotels near the convention center 3+ weeks ahead for a fair of this scale.",
    nearbyClusters: "Shenzhen/Dongguan plastics & molds, Dongguan packaging plants, Foshan appliance-and-production-line suppliers.",
    source: "https://www.chinaplasonline.com/",
    lastVerified: "2026-09-20",
    verified: true,
    registrationLink: "https://www.chinaplasonline.com/ (Visitor Pre-registration)",
    faqs: [
      ["Is CHINAPLAS relevant if I only buy packaging?", "Yes — packaging extrusion, film and converting equipment form a major hall share alongside materials."],
      ["Should we demo machines at the fair or at the factory?", "Both: fairs give fast comparisons; our supplier-trip service schedules live factory demonstrations for finalists."],
    ],
  },
};

// Deep industry content: each key is industry slug.
export const INDUSTRY_DEEP = {
  "furniture-building-materials": {
    buyerQuestions: [
      "Can Chinese factories meet our hotel-fit-out lead times and finishes we approve?",
      "How do MOQs work across mixed furniture orders (chairs, tables, beds from one brand)?",
      "Is solid wood really solid wood — and what is the honest difference at each price point?",
    ],
    moqSampling: "Case goods & upholstery: typically 20–100 pcs per SKU; mixed-container or LCL orders are normal. Sample cost 1–3× bulk price but often rebated on orders.",
    screeningPoints: "Own workshop vs trading company vs showroom reseller; joinery and hardware spec; capacity during Chinese New Year weeks; export packing.",
    factoryChecks: ["Materials in-store match catalog claims", "Assembly line for your quantity", "Finished-goods QC station", "Loading bay & packing method"],
    commonRisks: "Finish/mix risk on stained wood, foam quality in unseen upholstery, wrong dimension interpretation from drawings, weak export packing.",
    showLinks: ["canton-fair", "ciff-guangzhou"],
    clusters: "Guangzhou–Foshan Lecong (retail + factories), Dongguan (upper-mid finished furniture), Shunde (case goods), Foshan doors/windows, Jiangmen bathroom cabinets.",
    sampleRoute: "Day 1 CIFF fair halls → Day 2 Lecong showrooms (4–5 stops) → Day 3 Dongguan factories → comparison sheet & follow-up rounds.",
    expectedStandard: "已核实：CIFF官方2027年档期。经验判断：各产业带间车程与接待安排。待客户确认：具体交期与海关无偿限制按订单实际执行。",
  },
  "hospitality-equipment": {
    buyerQuestions: [
      "Do Chinese kitchen-lines match our local voltage (110V/230V), gas type and certification?",
      "Can we buy one fridge of each type instead of fifty of one type?",
      "Who supports installation and parts after we import?",
    ],
    moqSampling: "Small-orders often workable per SKU (1–5 pcs) since restaurants buy mixed ranges; sample/demo usually arranged in showrooms, not land-rush quotes.",
    screeningPoints: "Control-board quality, certification for destination, wiring harness, after-sales parts policy, ability to mix SKUs per container.",
    factoryChecks: ["Workshop may be outsourced — verify who owns the line", "Spare-parts workshop & tested running machines", "Assembly QC records"],
    commonRisks: "Voltage/gas mismatch discovered after shipment, cables & plugs, missing local-service partners at destination.",
    showLinks: ["canton-fair", "hotelex-shanghai"],
    clusters: "Guangzhou (厨具市场), Foshan stainless fabrication, Jiangmen & Shenzhen coffee/tea equipment.",
    sampleRoute: "HOTELEX fair day + supplier visits in Panyu/Foshan; demo-machines on first visits, then quote rounds with spare-parts terms.",
    expectedStandard: "已核实：HOTELEX国际采购团情况。经验判断：为开店项目准备的具体整合报价。待客户确认：电压、燃气种类与目的地服务网络。",
  },
  "beauty-packaging": {
    buyerQuestions: [
      "Who owns the mold when we order custom bottles — and what happens on repeat runs?",
      "How many decoration steps (silk-screen/hot-stamp/frosting) fit a small brand's unit economics?",
      "Will the sample I approve be the reality at scale?",
    ],
    moqSampling: "Stock packaging starts as low as a few thousand pcs; full custom mold 10k+ pcs with tooling fee. Color/decoration sampling typically 7–15 days.",
    screeningPoints: "Decoration in-house vs outsourced, mold ownership terms, tolerance data, sample lineage documentation.",
    factoryChecks: ["Decoration workshop dust control", "Quality-check on pump–bottle fit tolerance", "Coating-line consistency checks"],
    commonRisks: "Decoration failures at scale, mold-tolerance drift between toolings, market-specific compliance left unverified.",
    showLinks: ["china-beauty-expo", "canton-fair"],
    clusters: "Jiangsu/Yangzhou (glass), Zhejiang/ningbo pumps & plastics, Guangzhou cosmetics OEM, Shantou packaging tools.",
    sampleRoute: "CBE show day + Jiangsu/Zhejiang plant visits; bring a product brief with volumes and target price.",
    expectedStandard: "经验判断：美妆模具所有权为行业常态；务必写入合同。已核实：CBE的官方供应链配对活动真实存在。",
  },
  "pet-products": {
    buyerQuestions: [
      "Which materials pass EU/US child-level toy safety analogs for pet goods?",
      "What's a realistic first order for a new brand in toys/bedding/carriers?",
      "Do suppliers do custom prints for low volumes?",
    ],
    moqSampling: "500–2000 pcs per SKU is typical for toys; carriers/soft goods run higher. Printed fabrics often start at 500–1000 m for custom patterns.",
    screeningPoints: "Material composition, destination-market compliance documentation, real factory vs outsourcing chain, ability to hold printing repeat batches.",
    factoryChecks: ["Sewing line quality & stitching", "Materials warehouse classification", "Printing samples in matched colors"],
    commonRisks: "Compliance claims without lab-tests, overstated printing capacity, wrong animal-safety claims.",
    showLinks: ["cips", "canton-fair"],
    clusters: "Zhejiang Pingyang pet toys, Jiangsu Yangzhou soft goods, Shandong carriers, Guangdong electronics/smart accessories.",
    sampleRoute: "CIPS days + after-show supplier days eastern coastal belts.",
    expectedStandard: "已核实：CIPS 2026日期与地点。经验判断：合规与批次问题。待客户确认：目标市场合规文件真正验证。用专业机构验证，不由本站保证。",
  },
  "automotive-aftermarket": {
    buyerQuestions: [
      "Which quality tier does each supplier really serve — economy, mid or premium aftermarket?",
      "How is supplementary supply channel fitment handled (OE numbers, model applicability)?",
      "Will mixed-category containers be well-priced and well-packed?",
    ],
    moqSampling: "Running SKUs: 50–500 pcs even; workshop machines: single units at list price. Formats vary — some factories try full-container-only from stock lines.",
    screeningPoints: "Quality-tier honesty; packaging quality for Mixed loads; after-sales warranty dispatch to destination.",
    factoryChecks: ["CNC/measurement accuracy.", "Heat treatment & materials control", "Packaging per-kart, box strength"],
    commonRisks: "Fitment-matching errors, wrong segment positioning, inflated certification claims — verify critical certificates independently.",
    showLinks: ["automechanika-shanghai", "canton-fair"],
    clusters: "Yiwu (accessories), Ruian (filters & bumpers), Ningbo (brakes & suspension), Guangzhou (maintenance equipment).",
    sampleRoute: "Automechanika Shanghai days + matches around Zhejiang/Ningbo/Wenzhou factories.",
    expectedStandard: "经验判断：分类与档位策略。待客户确认：型号/欧码兼容性由专业核实。",
  },
  "industrial-machinery": {
    buyerQuestions: [
      "Will commissioning happen at the factory or after delivery — and who pays parts failures?",
      "What exactly drives price difference between a 2% spec match and 95% match machines?",
      "Who trains our operators — remote or on-site?",
    ],
    moqSampling: "Unit-based (1 line/machine). They evaluate order value & service loads: budget forecast attached to the RFQ.",
    screeningPoints: "Configuration transparency (motor/drive brand), order book position, factory's willingness to run live demo at the buyer's volume, spares plan.",
    factoryChecks: ["Machining accuracy of finished line", "Electrical cabinet assembly standards", "Run test with your material/product"],
    commonRisks: "Spec reductions during production, weak after-sales parts availability, unrealistic daily-output promises.",
    showLinks: ["canton-fair", "chinaplas"],
    clusters: "Guangzhou packaging machinery, Dongguan/Suzhou food processing, Ningbo plastics, Wenzhou paper equipment.",
    sampleRoute: "CHINAPLAS/Canton Fair days + plant visits with machine demonstration; decisions take notes by third-party technical partner.",
    expectedStandard: "专业边界：选型由技术伙伴判断，本站做协调与记录。已核实：CHINAPLAS轮换城市待年度确认。",
  },
  "fashion-textiles": {
    buyerQuestions: [
      "Can grafting samples from a sketch be trusted without a physical sample round?",
      "How do we buy small-batch fabric rolls (200–500m) with consistent dye lots?",
      "Who owns grading & fitting changes during sampling loops?",
    ],
    moqSampling: "Fabric: 500–1000 m per colorway; garment sampling: 1–10 pcs, 7–15 days; whole-collection programs need 60–90 days.",
    screeningPoints: "In-house pattern room vs outsourced, dye-lot documentation capability, sample-stocking speed, remote-buyer communication quality.",
    factoryChecks: ["Pattern room sample precision", "Dye/finishing consistency", "Sewing line fit-checks records"],
    commonRisks: "Dye-lot drift between repeat runs, late sampling loops, port-changes when both sampling and production extend beyond the calendar.",
    showLinks: ["intertextile-shanghai", "canton-fair"],
    clusters: "Guangzhou fabric markets (Zhongda), Keqiao (Shaoxing) fabric city, Dongguan/Chaozhou footwear, Humen apparel town.",
    sampleRoute: "Intertextile days + Guangzhou fabric market half-day + shoe/bag sample routes.",
    expectedStandard: "经验判断：产业带内可选供应商的宽度与深度。待客户确认：样品与交期实际窗口。",
  },
  "electronics-general-merchandise": {
    buyerQuestions: [
      "Which certifications does this device actually hold for our marketplace (CE / FCC / UKCA / …)?",
      "How do I buy small volumes of electronics without full container sets?",
      "When ordering generic items, how do quality tiers compare on build quality?",
    ],
    moqSampling: "Factory-direct: 500–1000 per SKU; trading companies: 100–500. Accessories even buy per-hundred from wholesale markets.",
    screeningPoints: "Real certification documents (not logo copies), box/packaging quality matched to your market, QC step in final assembly.",
    factoryChecks: ["End-of-line QC process", "Certification document audit", "Packaging drop-test samples"],
    commonRisks: "Marketplace safety take-downs from missing certification, low-grade freight/fakes in market channels.",
    showLinks: ["canton-fair", "global-sources-hong-kong"],
    clusters: "Shenzhen electronics ecosystem (Huaqiangbei), Dongguan accessories, Yiwu general merchandise, Guangzhou household goods.",
    sampleRoute: "Global Sources HK days + Shenzhen factory days in one trip; combined logistics route across the border.",
    expectedStandard: "经验判断：比价透明化。已核实：Shenzhen showing-clearly combination strongly preferred for electronics.",
  },
};

/* Deep records for sample/pricing structure: no committed prices, fields only. */
export const PRICING_EXAMPLES = [
  {
    id: "supply-chain-kickoff",
    name: "Supply-chain kickoff (remote)",
    who: "Companies starting or expanding a China supply chain — does not require a trip.",
    includes: ["Supplier research & structured screening", "Evidence-noted shortlist with per-supplier open questions", "Quote collection at your quantity (optional add)", "Comparison-ready deliverable you can forward internally"],
    passthroughs: ["Third-party audit / inspection fees, if commissioned, at actual provider rates"],
    commissionNote: "No supplier-side income in this format.",
    outOfScope: ["Quality certification", "Order guarantees", "Travel coordination (addable later)"],
  },
  {
    id: "show-escort-day",
    name: "Show-escort day",
    who: "Buyers already attending a fair who want one organized day of accompanied visit & interpreting.",
    includes: ["Coordination & pre-trip planning", "Business interpreter (day rate)", "Business vehicle (day rate)", "Meeting notes same evening"],
    passthroughs: ["Hotel, meals", "Fair entry cost if any (you pay the organizer)", "Parking/tolls"],
    commissionNote: "No supplier-side income in this format.",
    outOfScope: ["Supplier shortlist research (bookable separately)", "Factory scheduling"],
  },
  {
    id: "three-day-show-sourcing",
    name: "3-day trade show + supplier visits",
    who: "Buyers anchoring one fair and extending with supplier/showroom days around it.",
    includes: ["Trip plan & hotel options", "Supplier shortlist (5–8 candidates) built pre-trip", "Accompanied visit days & interpreting", "Comparison sheet + 2 follow-up rounds"],
    passthroughs: ["Hotels, transport, meals", "Third-party costs at actual rates (done after your confirmation)"],
    commissionNote: "Where supplier-side income exists, disclosed above — never folded invisibly into a supplier we recommend.",
    outOfScope: ["Quality certification", "Order guarantees"],
  },
  {
    id: "five-seven-full-trip",
    name: "5–7 day full sourcing trip",
    who: "Buyers building a multi-supplier buying program across districts (furniture + lighting; machine + packaging; textile + sampling...).",
    includes: ["Full requirement brief & route design", "Supplier shortlist, reviews & appointments per specialty", "Accompanied days with records", "Post-trip coordination window (agreed)"],
    passthroughs: ["Hotels, intercity transport", "Third parties (inspectors, forwarders) at actual rates"],
    commissionNote: "Supplier-side income by agreement, disclosed in the quote before you confirm; you keep multi-candidate selection.",
    outOfScope: ["We never own your goods", "No importer-of-record role"],
  },
];

/* Sample documents page content is generated as HTML directly in build. */
export const SAMPDOC_TITLES = {
  "sample-trip-plan": "Sample Trip Plan",
  "supplier-comparison": "Supplier Comparison Template",
  "factory-visit-checklist": "Factory Visit Checklist",
  "meeting-notes": "Meeting Notes Template",
};
