// photos v2 — evidence strip. CC-licensed, attribute page: /photo-credits/
// Verified via Commons API 2026-09-20 (artist/license fields echoed from extmetadata, never guessed).
export const PHOTOS = [
  { file: "/img/canton-fair-complex.webp", title: "Canton Fair Complex East Station 20210118.jpg", artist: "Tim Wu", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Canton_Fair_Complex_East_Station_20210118.jpg", caption: "The Canton Fair Complex (Pazhou), Guangzhou — the fair venue our trips are planned around.", alt: "Canton Fair Complex (Pazhou) exterior halls, Guangzhou" },
  { file: "/img/canton-fair-hall.webp", title: "China import and export fair - panoramio.jpg", artist: "long79", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:China_import_and_export_fair_-_panoramio.jpg", caption: "Inside a Canton Fair hall — supplier booths and buyer meetings.", alt: "Inside a trade fair hall with supplier booths" },
  { file: "/img/factory-line.webp", title: "BML Bamailong factory workers 1-013.jpg", artist: "YeraC", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:BML_Bamailong_factory_workers_1-013.jpg", caption: "On the production line — factory-visit mornings are where claims actually get verified.", alt: "Workers on a Chinese production line" },
  { file: "/img/business-interpreting.webp", title: "Horasis Global China Business Meeting - simultaneous interpretation (10865545724).jpg", artist: "Richter Frank-Jurgen", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Horasis_Global_China_Business_Meeting_-_simultaneous_interpretation_(10865545724).jpg", caption: "Business meeting behind interpreter — clean two-way communication matters more than flawless words.", alt: "Business meeting with consecutive interpreting" },
  { file: "/img/packaging-line.webp", title: "Plastic Woven Bag Production Line Pic 1.jpg", artist: "Zhangzj cet", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Plastic_Woven_Bag_Production_Line_Pic_1.jpg", caption: "Packaging production line — an industrial route we run for machinery buyers.", alt: "Packaging production line in a factory" },
  { file: "/img/sniec.webp", title: "Shanghai new international expo centre.jpg", artist: "Pyzhou", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Shanghai_new_international_expo_centre.jpg", caption: "Shanghai New International Expo Centre (SNIEC) — anchor venue for Shanghai fairs.", alt: "SNIEC exhibition halls, Shanghai" },
  { file: "/img/yiwu-market.webp", title: "Yiwu Market.jpg", artist: "Cherubby", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Yiwu_Market.jpg", caption: "Yiwu wholesale market — small-lot merchandise from many suppliers under one roof.", alt: "Interior of Yiwu wholesale market" },
  { file: "/img/shenzhen-world.webp", title: "Shenzhen World Exhibition & Convention Center (2).jpg", artist: "Dinkun Chen", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Shenzhen_World_Exhibition_%26_Convention_Center_(2).jpg", caption: "Shenzhen World Exhibition & Convention Center (Bao'an) — CHINAPLAS venue.", alt: "Shenzhen World convention center" },
  { file: "/img/pazhou-hall.webp", title: "中国进出口商品交易会展馆.JPG", artist: "H2NCH2COOH", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:中国进出口商品交易会展馆.JPG", caption: "Pazhou exhibition halls, Guangzhou — fair days route into sourcing days.", alt: "Pazhou exhibition area, Guangzhou" },
];
